# Use command below to load the environment variables manually or use the .nttmcp file
# set +o history
# export NTTMCP_API=api-<geo>.mcp-services.net
# export NTTMCP_API_VERSION=2.11
# export NTTMCP_PASSWORD=mypassword
# export NTTMCP_USER=myusername
# set -o history

- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    # cnd: 'SAPDRS_POC'
    cnd: 'Advanced_POC'
    region: 'na'
    datacenter: 'GEN_SAP1_GEO1_3'
    # auth:
    #   username: '{{ NTTMCP_USER }}'
    #   password: '{{ NTTMCP_PASSWORD }}'
    #   api: '{{ NTTMCP_API }}'
    #   api_version: '{{ NTTMCP_API_VERSION }}'
  tasks:
  - name: List Cloud Network Domains
    nttmcp.mcp.network_info:
      # auth: "{{auth}}"
      region: "{{ region }}"
      datacenter: "{{ datacenter }}"
    register: output
    tags:
    - init
  # - debug: var=output.data.network_domain
  - set_fact:
      network_domain_list: "{{ output.data.network_domain }}"
    tags:
    - init
  
  - name: Network Domain List
    debug: var=network_domain_list
    tags:
    - init

  - name: Loop thru Domain List
    debug:
      msg: "Network Domain Name:{{ item.name }}, datacenterid {{ item.datacenterId}}"
    with_items: "{{ network_domain_list }}"
    tags:
    - init
  - copy:
      content: '{{output | to_nice_json }}'
      dest: ./output/cloud_network_domains.json
    delegate_to: localhost
    tags:
    - init

  # - name: List Specific Cloud Network Domains
  #   nttmcp.mcp.network_info:
  #     # auth: "{{auth}}"
  #     region: "{{ region }}"
  #     datacenter: "{{ datacenter }}"
  #     name: '{{ cnd }}'
  #   register: output
  # - debug: var=output
  # - copy:
  #     content: '{{output | to_nice_json }}'
  #     dest: ./output/network_info.json
  #   delegate_to: localhost

  # - name: List all firewall rules within a Cloud Network Domain``
  #   nttmcp.mcp.firewall_info:
  #     # auth: "{{auth}}"
  #     region: "{{ region }}"
  #     datacenter: "{{ datacenter }}"
  #     network_domain: "{{ cnd }}"
  #   register: output
  # - debug: var=output
  # - copy:
  #     content: '{{output | to_nice_json }}'
  #     dest: ./output/firewall.json
  #   delegate_to: localhost


  # - name: List all servers
  #   nttmcp.mcp.server_info:
  #     # auth: "{{auth}}"
  #     region: "{{ region }}"
  #     datacenter: "{{ datacenter }}"
  #     network_domain: '{{ cnd }}'
  #   register: output
  # - debug: var=output
  # - copy:
  #     content: '{{output | to_nice_json }}'
  #     dest: ./output/servers.json
  #   delegate_to: localhost
  

  # - name: List all Server Security Groups in a Network Domain
  #   nttmcp.mcp.sec_group_info:
  #     # auth: "{{auth}}"
  #     region: "{{ region }}"
  #     datacenter: "{{ datacenter }}"
  #     network_domain: '{{ cnd }}'
  #     type: server
  #   register: output
  # - debug: var=output
  # - copy:
  #     content: '{{output | to_nice_json }}'
  #     dest: ./output/security_group_servers.json
  #   delegate_to: localhost


  # - name: List all VLAN Security Groups in a Network Domain
  #   nttmcp.mcp.sec_group_info:
  #     # auth: "{{auth}}"
  #     region: "{{ region }}"
  #     datacenter: "{{ datacenter }}"
  #     network_domain: '{{ cnd }}'
  #     type: vlan
  #   register: output
  # - debug: var=output
  # - copy:
  #     content: '{{output | to_nice_json }}'
  #     dest: ./output/security_group_vlan.json
  #   delegate_to: localhost

  - name: List Port Lists
    nttmcp.mcp.port_list_info:
      # auth: "{{auth}}"
      region: "{{ region }}"
      datacenter: "{{ datacenter }}"
      network_domain: '{{ cnd }}'
    register: output
  - debug: var=output
  - copy:
      content: '{{output | to_nice_json }}'
      dest: ./output/port_list.json
    delegate_to: localhost

  - name: List all IP address lists for a Cloud Network Domain
    nttmcp.mcp.ip_list_info:
      # auth: "{{auth}}"
      region: "{{ region }}"
      datacenter: "{{ datacenter }}"
      network_domain: '{{ cnd }}'
    register: output
  - debug: var=output
  - copy:
      content: '{{output | to_nice_json }}'
      dest: ./output/ip_list.json
    delegate_to: localhost



  
  # - name: List static routes
  #   nttmcp.mcp.static_route_info:
  #     # auth: "{{auth}}"
  #     region: "{{ region }}"
  #     datacenter: "{{ datacenter }}"
  #     network_domain: '{{ cnd }}'
  #   register: output
  # - debug: var=output
  # - copy:
  #     content: '{{output | to_nice_json }}'
  #     dest: ./output/static_routes.json
  #   delegate_to: localhost


  - name: Nat Info Block
    block:
    - name: List nat info within a Cloud Network Domain
      nttmcp.mcp.nat_info:
        # auth: "{{auth}}"
        region: "{{ region }}"
        datacenter: "{{ datacenter }}"
        network_domain: '{{ cnd }}'
      register: output
    - debug: var=output
    - copy:
        content: '{{output | to_nice_json }}'
        dest: "./output/nat_{{ cnd }}.json"
      delegate_to: localhost
    tags:
    - manual

  - name: VIP Virtual Listener Info Block
    block:
    - name: List virtual listener info within a Cloud Network Domain
      nttmcp.mcp.vip_listener_info:
        # auth: "{{auth}}"
        region: "{{ region }}"
        datacenter: "{{ datacenter }}"
        network_domain: '{{ cnd }}'
      register: output
    - debug: var=output
    - copy:
        content: '{{output | to_nice_json }}'
        dest: "./output/vip_listener_{{ cnd }}.json"
      delegate_to: localhost
    tags:
    - manual

  - name: VIP SSL Info Block
    block:
    - name: List virtual listener SSL info within a Cloud Network Domain
      nttmcp.mcp.vip_ssl_info:
        # auth: "{{auth}}"
        region: "{{ region }}"
        datacenter: "{{ datacenter }}"
        network_domain: '{{ cnd }}'
      register: output
    - debug: var=output
    - copy:
        content: '{{output | to_nice_json }}'
        dest: "./output/vip_ssl_{{ cnd }}.json"
      delegate_to: localhost
    tags:
    - manual

  - name: VIP pool Info Block
    block:
    - name: List virtual pool info within a Cloud Network Domain
      nttmcp.mcp.vip_pool_info:
        # auth: "{{auth}}"
        region: "{{ region }}"
        datacenter: "{{ datacenter }}"
        network_domain: '{{ cnd }}'
      register: output
    - debug: var=output
    - copy:
        content: '{{output | to_nice_json }}'
        dest: "./output/vip_pool_{{ cnd }}.json"
      delegate_to: localhost
    tags:
    - manual

  - name: SNAT Info Block
    block:
    - name: List SNAT info within a Cloud Network Domain
      nttmcp.mcp.snat_info:
        # auth: "{{auth}}"
        region: "{{ region }}"
        datacenter: "{{ datacenter }}"
        network_domain: '{{ cnd }}'
      register: output
    - debug: var=output
    - copy:
        content: '{{output | to_nice_json }}'
        dest: "./output/snat_{{ cnd }}.json"
      delegate_to: localhost
    tags:
    - manual


  - name: Static Route Info Block
    block:
    - name: List Static Route info within a Cloud Network Domain
      nttmcp.mcp.static_route_info:
        # auth: "{{auth}}"
        region: "{{ region }}"
        datacenter: "{{ datacenter }}"
        network_domain: '{{ cnd }}'
      register: output
    - debug: var=output
    - copy:
        content: '{{output | to_nice_json }}'
        dest: "./output/static_route_{{ cnd }}.json"
      delegate_to: localhost
    tags:
    - manual

  - name: Ipam Info Block
    block:
    - name: List IPAM info within a Cloud Network Domain
      nttmcp.mcp.ipam_info:
        # auth: "{{auth}}"
        region: "{{ region }}"
        datacenter: "{{ datacenter }}"
        network_domain: '{{ cnd }}'
      register: output
    - debug: var=output
    - copy:
        content: '{{output | to_nice_json }}'
        dest: "./output/ipam_{{ cnd }}.json"
      delegate_to: localhost
    tags:
    - manual

  - name: Server AntiAfinity Info Block
    block:
    - name: List Anti Affinity info within a Cloud Network Domain
      nttmcp.mcp.ipam_info:
        # auth: "{{auth}}"
        region: "{{ region }}"
        datacenter: "{{ datacenter }}"
        network_domain: '{{ cnd }}'
      register: output
    - debug: var=output
    - copy:
        content: '{{output | to_nice_json }}'
        dest: "./output/anti_affinity_{{ cnd }}.json"
      delegate_to: localhost
    tags:
    - manual

##### Task List Loops

  - name: Loop thru Domain List
    debug:
      msg: "Network Domain Name:{{ item.name }}, datacenterid {{ item.datacenterId}}"
    with_items: "{{ network_domain_list }}"

  # - name: List all VLANS per Network Domain
  #   include_tasks: task_list_vlans.yml
  #   with_items: "{{ network_domain_list }}"

  - name: List all Firewall Rules per Network Domain
    include_tasks: task_list_firewall.yml
    with_items: "{{ network_domain_list }}"
    tags:
    - firewall 
    - all

  - name: List all Security Groups per Network Domain
    include_tasks: task_list_secgroup.yml
    with_items: "{{ network_domain_list }}"
    tags:
    - secgroup 
    - all


  - name: List all Nat Info per Network Domain
    include_tasks: task_list_nat.yml
    with_items: "{{ network_domain_list }}"
    tags:
    - nat
    - all

  - name: List all Vip Listener Info per Network Domain
    include_tasks: task_list_vip_listener.yml
    with_items: "{{ network_domain_list }}"
    tags:
    - viplistener
    - all

  # - name: List all VLANs per Network Domain
  #   block:
  #     - name: List all vlan for {{ item.name }}
  #       nttmcp.mcp.vlan_info:
  #         # auth: "{{auth}}"
  #         region: "{{ region }}"
  #         datacenter: "{{ datacenter }}"
  #         network_domain: '{{ item.name }}'
  #       register: output
  #     - debug: var=output
  #     - copy:
  #         content: '{{output | to_nice_json }}'
  #         dest: "./output/vlans_{{ item.name }}.json"
  #       delegate_to: localhost
  #   with_items: "{{ network_domain_list }}"